dictionaries:
  - en
  - en_GB

excluded_words:
  - rnaseq
  - ipynb
  - bamqc
  - qualimap
  - GDC's
  - gdc-mrnaseq-pipeline
  - gdc-reference-genome
  - ENCODE's
  - encode-rnaseq-pipeline
  - gtex-rnaseq-pipeline
  - sjdbOverhang
  - exome
  - omics
  - omics-based
  - fastqc
  - ngsderive
  - SamToFastq
  - fastq
  - fastq-screen
  - unstranded
  - conda
  - bioconda
  - conda-forge
  - multiqc
  - fastqs
  - fqlib
  - readlen
  - gtf
  - Illumina
